# Generated by Django 4.1.7 on 2023-11-19 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
        ('farms', '0002_alter_farm_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='seed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seeds.seeds'),
        ),
    ]
