# Generated by Django 4.1.7 on 2023-11-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_alter_parcel_seed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farms.farm'),
        ),
    ]
