# Generated by Django 4.1.7 on 2023-12-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_parcel_farm_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='farm_id',
            new_name='farm',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='seed_id',
            new_name='seed',
        ),
        migrations.AlterField(
            model_name='farm',
            name='date_creation_farm',
            field=models.DateField(auto_now=True),
        ),
    ]
